name: Storage
version: 1.0
main: de.mcbesser.storage.Storage
api-version: '1.20'
authors: [mcbesser]
description: "Ein fortschrittliches Lager-System f\u00fcr Minecraft."
permissions:
  storage.use:
    description: Erlaubt die Nutzung des Lager-Systems.
    default: true
